// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASq8LHyQOMvME6WhP3DSA_JlWNmkTsdHQ',
    appId: '1:331708644926:web:57baca43b88fb356ac5b6f',
    messagingSenderId: '331708644926',
    projectId: 'tienda-productos-b7ff7',
    authDomain: 'tienda-productos-b7ff7.firebaseapp.com',
    databaseURL: 'https://tienda-productos-b7ff7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tienda-productos-b7ff7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM_IcYBY9SasOKsVAFoCrkZPY_OZ8Vclg',
    appId: '1:331708644926:android:4328bc5a21c1edaeac5b6f',
    messagingSenderId: '331708644926',
    projectId: 'tienda-productos-b7ff7',
    databaseURL: 'https://tienda-productos-b7ff7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tienda-productos-b7ff7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASq8LHyQOMvME6WhP3DSA_JlWNmkTsdHQ',
    appId: '1:331708644926:web:2d8800d658b464a0ac5b6f',
    messagingSenderId: '331708644926',
    projectId: 'tienda-productos-b7ff7',
    authDomain: 'tienda-productos-b7ff7.firebaseapp.com',
    databaseURL: 'https://tienda-productos-b7ff7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tienda-productos-b7ff7.firebasestorage.app',
  );
}
